image: archlinux
packages:
  - cargo
secrets:
  - 61c66951-0de4-4091-8803-b9dda7f6f66d
sources:
  - https://git.sr.ht/~nixgoat/shoelace
tasks:
  - mirror: |
      cd shoelace
      git remote set-head origin -d
      ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts
      git push --prune git@github.com:otoayana/shoelace.git '+refs/remotes/origin/*:refs/heads/*' '+refs/tags/*:refs/tags/*'
  - build: |
      cd shoelace
      cargo build --release
  - test: |
      cd shoelace
      cargo test --release
